'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UtilidadesLince.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property lincew_20120918_131046_15000() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lincew_20120918_131046_15000", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1-0070	PLAYGROUND TF		02	850	0	0
        '''1-0070	PLAYGROUND TF	42	02	850	1	2
        '''1-0070	PLAYGROUND TF	43	02	850	2	2
        '''1-0070	PLAYGROUND TF	44	02	850	2	2
        '''1-0070	PLAYGROUND TF	45	02	850	1	1
        '''1-0072	PLAYGRAUND TF BLACK-WHITE		02	850	0	0
        '''1-0072	PLAYGRAUND TF BLACK-WHITE	41	02	850	1	1
        '''1-0072	PLAYGRAUND TF BLACK-WHITE	42	02	850	4	3
        '''1-0072	PLAYGRAUND TF BLACK-WHITE	43	02	850	1	1
        '''1-0072	PLAYGRAUND TF BLACK-WHITE	44	02	850	2	2
        '''1-0074	PLAYGROUND TF		02	850	0	0
        '''1-0074	PLAYGROUND TF	42	02	850	2	2
        '''1-0074	PLAYGROUND TF	43	02 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Prueba_inventario() As String
            Get
                Return ResourceManager.GetString("Prueba_inventario", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
